
services:
  db:
    container_name: cont_mysql
    image: mysql:latest
    restart: always
    command:
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE : db_first
      MYSQL_USER: user
      MYSQL_PASSWORD: userpwd
    volumes: 
      - ./ressources:/ressourcesSQL000

  adminer:
    container_name: cont_adminer
    image: adminer
    restart: always
    ports: 
      - 8080:8080

